; docker/php/99-overrides.ini
; If you change php ini overrides after container was build
; and do not want to rebuild container, apply with:
; docker compose restart php
max_file_uploads= 50
upload_max_filesize=50M
post_max_size=200M
max_execution_time=180
memory_limit=1024M
