# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    twig:
        mode: lazy
    
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public/"
                cache_prefix: media/cache
    loaders:
        default:
            filesystem:
                data_root: "%env(PUBLIC_DIR_SYSTEM_PATH)%" # public path fed to liip filter
    
    driver: imagick

    default_filter_set_settings:
        format: avif
    
    filter_sets:
        thumb_small:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound # forces square aspect ratio
        # thumb_card Size and cropping logic ***
        # use 'outbound' to force the image aspect ratio, which makes the card grid layout easier to handle
        # Note about grid layout:
        #   object-fit:cover is useful to force aspect ratio dynamically, but forcing the aspect ratio inside the grid
        #   (by setting aspect-ratio for a grid element) works against the grid flexibility to adapt to its content
        #   If we force aspect-ratio to the image grid item, the rest of the card won't be able to adapt as well
        #   and we can run into bugs where the other grid element overflows into the image if it has too much content
        #   On the other hand, if we force aspect ratio on the image at thumb creation, then we can use object-fit to
        #   make the image item adapt to the changing size of the grid and let it adapt to the content.
        # use 'allow_upscale' and 'background' to force the image aspect ratio *even if original is smaller*
        # (additional space is filled with background)
        # 600x600 logic: phones are supposed to go up to 480px (logical/CSS pixels, not real pixels)
        # devices up to 768px include large phones and small tablets

        # FIXED SIZES
        # ===========
        # mode 'outbound' forces aspect-ratio to size[] array

        # Square
        thumb_square_432: # max size for 1x pixel density for phone
            quality: 75
            filters:
                thumbnail: 
                    size: [432, 432]
                    mode: outbound
        thumb_square_640: # intermediate size, can be picked by browser when useful
            quality: 75
            filters:
                thumbnail: 
                    size: [640, 640]
                    mode: outbound
        thumb_square_864: # max size for 2x pixel density
            quality: 75
            filters:
                thumbnail: 
                    size: [864, 864]
                    mode: outbound
        # 4/3
        thumb_4_3_800: # max size for 1x pixel density
            quality: 75
            filters: 
                thumbnail:
                    size: [800, 600]
                    mode: outbound
        thumb_4_3_640: # max size for 1x pixel density
            quality: 75
            filters: 
                thumbnail:
                    size: [640, 480]
                    mode: outbound
        thumb_4_3_1280: # max size for 2x pixel density
            quality: 75
            filters: 
                thumbnail:
                    size: [1280, 920]
                    mode: outbound
        
        # VARYING SIZE
        # ============
        # mode 'inset' keeps original aspect ratio, bound by size[] array

        thumb_large:
            quality: 75
            filters:
                thumbnail:
                    size: [2000, 1300]
                    mode: inset