ux_icons:
    aliases:
        theme: 'ix:light-dark'
        home: 'ph:house'
        back: 'ic:round-arrow-back-ios'
        forward: 'ic:round-arrow-forward-ios'
        trash: 'lucide:trash-2'
        account: 'qlementine-icons:user-16'
        external-link: 'prime:external-link'
        info: 'lucide:info'
        settings: 'lucide:settings'
        filter: 'mage:filter'
        grab-horizontal: 'charm:grab-horizontal'
        grab-vertical: 'charm:grab-vertical'
        dots: 'tabler:dots-vertical'
        show: 'ic:baseline-remove-red-eye'
        delete: 'ic:baseline-delete'
        language: 'mdi:language'
        login: 'material-symbols:login'
        logout: 'material-symbols:logout'
