<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250505153528 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE bakery_item (id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE breakfast (id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(2) DEFAULT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE dessert (id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE dish (id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE drink (id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE food_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, love_level INT NOT NULL, local_level INT NOT NULL, healthy_level INT NOT NULL, season_start INT DEFAULT NULL, season_end INT DEFAULT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE food_item_food_tag (food_item_id INT NOT NULL, food_tag_id INT NOT NULL, PRIMARY KEY(food_item_id, food_tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A22AB3625DF08E66 ON food_item_food_tag (food_item_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A22AB362FAFC09B2 ON food_item_food_tag (food_tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE food_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE fruit (id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE picture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, taken_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, highlight BOOLEAN DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, food_item_id INT DEFAULT NULL, dish_id INT DEFAULT NULL, breakfast_id INT DEFAULT NULL, drink_id INT DEFAULT NULL, bakery_item_id INT DEFAULT NULL, dessert_id INT DEFAULT NULL, fruit_id INT DEFAULT NULL, trip_id INT DEFAULT NULL, highlighted_trip_id INT DEFAULT NULL, place_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F895DF08E66 ON picture (food_item_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89148EB0CB ON picture (dish_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89442D22 ON picture (breakfast_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F8936AA4BB4 ON picture (drink_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89BA978F85 ON picture (bakery_item_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89745B52FD ON picture (dessert_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89BAC115F0 ON picture (fruit_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89A5BC2E0E ON picture (trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89A3AD38F ON picture (highlighted_trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89DA6A219 ON picture (place_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE picture_place_tag (picture_id INT NOT NULL, place_tag_id INT NOT NULL, PRIMARY KEY(picture_id, place_tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5E55DCCEE45BDBF ON picture_place_tag (picture_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5E55DCC181C6478 ON picture_place_tag (place_tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE picture_tag (picture_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(picture_id, tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_336D34B0EE45BDBF ON picture_tag (picture_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_336D34B0BAD26311 ON picture_tag (tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, google_place_id VARCHAR(64) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE place_place_tag (place_id INT NOT NULL, place_tag_id INT NOT NULL, PRIMARY KEY(place_id, place_tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_78A0580FDA6A219 ON place_place_tag (place_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_78A0580F181C6478 ON place_place_tag (place_tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE place_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, country_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C3BD172F92F3E70 ON place_tag (country_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at DATE NOT NULL, ended_at DATE NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, headline_fr VARCHAR(255) DEFAULT NULL, headline_en VARCHAR(255) DEFAULT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, key VARCHAR(100) NOT NULL, cover_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_7656F53B8A90ABA9 ON trip (key)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_7656F53B922726E9 ON trip (cover_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE trip_country (trip_id INT NOT NULL, country_id INT NOT NULL, PRIMARY KEY(trip_id, country_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_659F8CCBA5BC2E0E ON trip_country (trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_659F8CCBF92F3E70 ON trip_country (country_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_ (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_language VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, last_login TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, last_active_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, verified BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, closed BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, hellbanned BOOLEAN NOT NULL, scam BOOLEAN DEFAULT NULL, demarchage BOOLEAN DEFAULT NULL, watchlist BOOLEAN NOT NULL, whitelist BOOLEAN NOT NULL, admin_reviewed BOOLEAN NOT NULL, kotcop_score DOUBLE PRECISION DEFAULT NULL, kotcop_updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON user_ (email)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE bakery_item ADD CONSTRAINT FK_C8E17FEEBF396750 FOREIGN KEY (id) REFERENCES food_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE breakfast ADD CONSTRAINT FK_8A0F4458BF396750 FOREIGN KEY (id) REFERENCES food_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE dessert ADD CONSTRAINT FK_79291B96BF396750 FOREIGN KEY (id) REFERENCES food_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE dish ADD CONSTRAINT FK_957D8CB8BF396750 FOREIGN KEY (id) REFERENCES food_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE drink ADD CONSTRAINT FK_DBE40D1BF396750 FOREIGN KEY (id) REFERENCES food_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_item_food_tag ADD CONSTRAINT FK_A22AB3625DF08E66 FOREIGN KEY (food_item_id) REFERENCES food_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_item_food_tag ADD CONSTRAINT FK_A22AB362FAFC09B2 FOREIGN KEY (food_tag_id) REFERENCES food_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE fruit ADD CONSTRAINT FK_A00BD297BF396750 FOREIGN KEY (id) REFERENCES food_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F895DF08E66 FOREIGN KEY (food_item_id) REFERENCES food_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89442D22 FOREIGN KEY (breakfast_id) REFERENCES breakfast (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F8936AA4BB4 FOREIGN KEY (drink_id) REFERENCES drink (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89BA978F85 FOREIGN KEY (bakery_item_id) REFERENCES bakery_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89745B52FD FOREIGN KEY (dessert_id) REFERENCES dessert (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89BAC115F0 FOREIGN KEY (fruit_id) REFERENCES fruit (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89A3AD38F FOREIGN KEY (highlighted_trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89DA6A219 FOREIGN KEY (place_id) REFERENCES place (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_place_tag ADD CONSTRAINT FK_5E55DCCEE45BDBF FOREIGN KEY (picture_id) REFERENCES picture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_place_tag ADD CONSTRAINT FK_5E55DCC181C6478 FOREIGN KEY (place_tag_id) REFERENCES place_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_tag ADD CONSTRAINT FK_336D34B0EE45BDBF FOREIGN KEY (picture_id) REFERENCES picture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_tag ADD CONSTRAINT FK_336D34B0BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_place_tag ADD CONSTRAINT FK_78A0580FDA6A219 FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_place_tag ADD CONSTRAINT FK_78A0580F181C6478 FOREIGN KEY (place_tag_id) REFERENCES place_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_tag ADD CONSTRAINT FK_C3BD172F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES user_ (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip ADD CONSTRAINT FK_7656F53B922726E9 FOREIGN KEY (cover_id) REFERENCES picture (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_country ADD CONSTRAINT FK_659F8CCBA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_country ADD CONSTRAINT FK_659F8CCBF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE bakery_item DROP CONSTRAINT FK_C8E17FEEBF396750
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE breakfast DROP CONSTRAINT FK_8A0F4458BF396750
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE dessert DROP CONSTRAINT FK_79291B96BF396750
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE dish DROP CONSTRAINT FK_957D8CB8BF396750
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE drink DROP CONSTRAINT FK_DBE40D1BF396750
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_item_food_tag DROP CONSTRAINT FK_A22AB3625DF08E66
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_item_food_tag DROP CONSTRAINT FK_A22AB362FAFC09B2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE fruit DROP CONSTRAINT FK_A00BD297BF396750
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F895DF08E66
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89148EB0CB
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89442D22
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F8936AA4BB4
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89BA978F85
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89745B52FD
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89BAC115F0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89A5BC2E0E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89A3AD38F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89DA6A219
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_place_tag DROP CONSTRAINT FK_5E55DCCEE45BDBF
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_place_tag DROP CONSTRAINT FK_5E55DCC181C6478
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_tag DROP CONSTRAINT FK_336D34B0EE45BDBF
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_tag DROP CONSTRAINT FK_336D34B0BAD26311
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_place_tag DROP CONSTRAINT FK_78A0580FDA6A219
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_place_tag DROP CONSTRAINT FK_78A0580F181C6478
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_tag DROP CONSTRAINT FK_C3BD172F92F3E70
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip DROP CONSTRAINT FK_7656F53B922726E9
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_country DROP CONSTRAINT FK_659F8CCBA5BC2E0E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_country DROP CONSTRAINT FK_659F8CCBF92F3E70
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE bakery_item
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE breakfast
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE country
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE dessert
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE dish
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE drink
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE food_item
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE food_item_food_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE food_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE fruit
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE ingredient
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE picture
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE picture_place_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE picture_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE place
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE place_place_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE place_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE reset_password_request
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trip
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trip_country
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE user_
        SQL);
    }
}
