<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260324105446 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE anonymous_page_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, path VARCHAR(255) NOT NULL, route_name VARCHAR(255) DEFAULT NULL, query_string TEXT DEFAULT NULL, referrer VARCHAR(1000) DEFAULT NULL, visit_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5AA897D675FA0FF2 ON anonymous_page_view (visit_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE anonymous_visit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id VARCHAR(128) NOT NULL, visitor_id VARCHAR(64) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, page_count INT NOT NULL, is_returning BOOLEAN NOT NULL, country_code VARCHAR(2) DEFAULT NULL, city_name VARCHAR(120) DEFAULT NULL, first_path VARCHAR(255) DEFAULT NULL, landing_referrer VARCHAR(1000) DEFAULT NULL, user_agent VARCHAR(512) DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_E0A8ABBF613FECDF ON anonymous_visit (session_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE anonymous_page_view ADD CONSTRAINT FK_5AA897D675FA0FF2 FOREIGN KEY (visit_id) REFERENCES anonymous_visit (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE anonymous_page_view DROP CONSTRAINT FK_5AA897D675FA0FF2
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE anonymous_page_view
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE anonymous_visit
        SQL);
    }
}
