<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250812220412 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_highlight DROP CONSTRAINT fk_d4879963a5bc2e0e
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media DROP CONSTRAINT fk_6a2ca10cff8f974d
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trip_highlight
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX idx_6a2ca10cff8f974d
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media DROP trip_highlight_id
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE trip_highlight (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, trip_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_d4879963a5bc2e0e ON trip_highlight (trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_highlight ADD CONSTRAINT fk_d4879963a5bc2e0e FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media ADD trip_highlight_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media ADD CONSTRAINT fk_6a2ca10cff8f974d FOREIGN KEY (trip_highlight_id) REFERENCES trip_highlight (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_6a2ca10cff8f974d ON media (trip_highlight_id)
        SQL);
    }
}
