<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250811170337 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE site_highlight (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE trip_highlight (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, trip_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D4879963A5BC2E0E ON trip_highlight (trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_highlight ADD CONSTRAINT FK_D4879963A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media ADD trip_highlight_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media ADD site_highlight_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CFF8F974D FOREIGN KEY (trip_highlight_id) REFERENCES trip_highlight (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C399C4167 FOREIGN KEY (site_highlight_id) REFERENCES site_highlight (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6A2CA10CFF8F974D ON media (trip_highlight_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6A2CA10C399C4167 ON media (site_highlight_id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_highlight DROP CONSTRAINT FK_D4879963A5BC2E0E
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE site_highlight
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trip_highlight
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CFF8F974D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C399C4167
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_6A2CA10CFF8F974D
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_6A2CA10C399C4167
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media DROP trip_highlight_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media DROP site_highlight_id
        SQL);
    }
}
