<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250507112559 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(2) DEFAULT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE food (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, love_level INT NOT NULL, local_level INT NOT NULL, healthy_level INT NOT NULL, season_start INT DEFAULT NULL, season_end INT DEFAULT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE food_food_tag (food_id INT NOT NULL, food_tag_id INT NOT NULL, PRIMARY KEY(food_id, food_tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_DCA3707CBA8E87C4 ON food_food_tag (food_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_DCA3707CFAFC09B2 ON food_food_tag (food_tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE food_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE picture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, taken_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, highlight BOOLEAN DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, food_id INT DEFAULT NULL, trip_id INT DEFAULT NULL, highlighted_trip_id INT DEFAULT NULL, place_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89BA8E87C4 ON picture (food_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89A5BC2E0E ON picture (trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89A3AD38F ON picture (highlighted_trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_16DB4F89DA6A219 ON picture (place_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE picture_place_tag (picture_id INT NOT NULL, place_tag_id INT NOT NULL, PRIMARY KEY(picture_id, place_tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5E55DCCEE45BDBF ON picture_place_tag (picture_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5E55DCC181C6478 ON picture_place_tag (place_tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE picture_tag (picture_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(picture_id, tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_336D34B0EE45BDBF ON picture_tag (picture_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_336D34B0BAD26311 ON picture_tag (tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, google_place_id VARCHAR(64) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE place_place_tag (place_id INT NOT NULL, place_tag_id INT NOT NULL, PRIMARY KEY(place_id, place_tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_78A0580FDA6A219 ON place_place_tag (place_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_78A0580F181C6478 ON place_place_tag (place_tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE place_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, country_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C3BD172F92F3E70 ON place_tag (country_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, headline_fr VARCHAR(255) DEFAULT NULL, headline_en VARCHAR(255) DEFAULT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, key VARCHAR(100) NOT NULL, started_at DATE NOT NULL, ended_at DATE NOT NULL, cover_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_7656F53B8A90ABA9 ON trip (key)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_7656F53B922726E9 ON trip (cover_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE trip_country (trip_id INT NOT NULL, country_id INT NOT NULL, PRIMARY KEY(trip_id, country_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_659F8CCBA5BC2E0E ON trip_country (trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_659F8CCBF92F3E70 ON trip_country (country_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE trip_trip_tag (trip_id INT NOT NULL, trip_tag_id INT NOT NULL, PRIMARY KEY(trip_id, trip_tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_27117D29A5BC2E0E ON trip_trip_tag (trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_27117D2955DD38BB ON trip_trip_tag (trip_tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE trip_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(100) NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, slug_fr VARCHAR(100) NOT NULL, slug_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_8F404E398A90ABA9 ON trip_tag (key)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_ (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_language VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, last_login TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, last_active_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, verified BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, closed BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, hellbanned BOOLEAN NOT NULL, scam BOOLEAN DEFAULT NULL, demarchage BOOLEAN DEFAULT NULL, watchlist BOOLEAN NOT NULL, whitelist BOOLEAN NOT NULL, admin_reviewed BOOLEAN NOT NULL, kotcop_score DOUBLE PRECISION DEFAULT NULL, kotcop_updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON user_ (email)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_food_tag ADD CONSTRAINT FK_DCA3707CBA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_food_tag ADD CONSTRAINT FK_DCA3707CFAFC09B2 FOREIGN KEY (food_tag_id) REFERENCES food_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89BA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89A3AD38F FOREIGN KEY (highlighted_trip_id) REFERENCES trip (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89DA6A219 FOREIGN KEY (place_id) REFERENCES place (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_place_tag ADD CONSTRAINT FK_5E55DCCEE45BDBF FOREIGN KEY (picture_id) REFERENCES picture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_place_tag ADD CONSTRAINT FK_5E55DCC181C6478 FOREIGN KEY (place_tag_id) REFERENCES place_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_tag ADD CONSTRAINT FK_336D34B0EE45BDBF FOREIGN KEY (picture_id) REFERENCES picture (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_tag ADD CONSTRAINT FK_336D34B0BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_place_tag ADD CONSTRAINT FK_78A0580FDA6A219 FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_place_tag ADD CONSTRAINT FK_78A0580F181C6478 FOREIGN KEY (place_tag_id) REFERENCES place_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_tag ADD CONSTRAINT FK_C3BD172F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES user_ (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip ADD CONSTRAINT FK_7656F53B922726E9 FOREIGN KEY (cover_id) REFERENCES picture (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_country ADD CONSTRAINT FK_659F8CCBA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_country ADD CONSTRAINT FK_659F8CCBF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_trip_tag ADD CONSTRAINT FK_27117D29A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_trip_tag ADD CONSTRAINT FK_27117D2955DD38BB FOREIGN KEY (trip_tag_id) REFERENCES trip_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE food_food_tag DROP CONSTRAINT FK_DCA3707CBA8E87C4
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE food_food_tag DROP CONSTRAINT FK_DCA3707CFAFC09B2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89BA8E87C4
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89A5BC2E0E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89A3AD38F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89DA6A219
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_place_tag DROP CONSTRAINT FK_5E55DCCEE45BDBF
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_place_tag DROP CONSTRAINT FK_5E55DCC181C6478
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_tag DROP CONSTRAINT FK_336D34B0EE45BDBF
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE picture_tag DROP CONSTRAINT FK_336D34B0BAD26311
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_place_tag DROP CONSTRAINT FK_78A0580FDA6A219
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_place_tag DROP CONSTRAINT FK_78A0580F181C6478
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE place_tag DROP CONSTRAINT FK_C3BD172F92F3E70
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip DROP CONSTRAINT FK_7656F53B922726E9
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_country DROP CONSTRAINT FK_659F8CCBA5BC2E0E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_country DROP CONSTRAINT FK_659F8CCBF92F3E70
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_trip_tag DROP CONSTRAINT FK_27117D29A5BC2E0E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE trip_trip_tag DROP CONSTRAINT FK_27117D2955DD38BB
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE country
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE food
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE food_food_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE food_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE ingredient
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE picture
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE picture_place_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE picture_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE place
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE place_place_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE place_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE reset_password_request
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trip
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trip_country
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trip_trip_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trip_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE user_
        SQL);
    }
}
