<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250812221437 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE story (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, display_order INT DEFAULT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, description_fr TEXT DEFAULT NULL, description_en TEXT DEFAULT NULL, trip_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_EB560438A5BC2E0E ON story (trip_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE story ADD CONSTRAINT FK_EB560438A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media ADD story_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CAA5D4036 FOREIGN KEY (story_id) REFERENCES story (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6A2CA10CAA5D4036 ON media (story_id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE story DROP CONSTRAINT FK_EB560438A5BC2E0E
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE story
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CAA5D4036
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_6A2CA10CAA5D4036
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE media DROP story_id
        SQL);
    }
}
