<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260329090556 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE anonymous_visitor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visitor_id VARCHAR(64) NOT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, page_count INT NOT NULL, user_agent VARCHAR(512) DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_anonymous_visitor_first_seen_at ON anonymous_visitor (first_seen_at)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_anonymous_visitor_last_seen_at ON anonymous_visitor (last_seen_at)
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX idx_anonymous_visit_started_at
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX idx_anonymous_visit_visitor_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE anonymous_visit DROP visitor_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE anonymous_visit DROP user_agent
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE anonymous_visit DROP alias
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE anonymous_visitor
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE anonymous_visit ADD visitor_id VARCHAR(64) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE anonymous_visit ADD user_agent VARCHAR(512) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE anonymous_visit ADD alias VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_anonymous_visit_started_at ON anonymous_visit (started_at)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_anonymous_visit_visitor_id ON anonymous_visit (visitor_id)
        SQL);
    }
}
