controllers:
    resource: '../src/Controller/'
    type: attribute
    prefix:
        fr: '/fr'
        en: ''

security_controllers:
    resource: '../src/Security/Controller/'
    type: attribute
    prefix:
        fr: '/fr'
        en: ''
