easy_admin:
    site_name: Guabao
    design:
        menu:
            - { entity: 'Video', icon: 'video'}
            - { entity: 'Channel', icon: 'youtube'}
            - { entity: 'Tag', icon: 'tag'}
            - { entity: 'Person', label: 'People', icon: 'user'}
            - { entity: 'Level', icon: 'star'}
            - { entity: 'Duration', icon: 'clock'}
    list:
        actions:
        - { name: 'show', icon: 'eye' }
        - { name: 'edit', icon: 'pencil' }
        - { name: 'delete', icon: 'trash' }
        collapse_actions: true
