easy_admin:
    entities:
        Channel:
            class: App\Entity\Channel
            list:
                sort: ['name', 'ASC']
            form:
                fields:
                    - name
                    - url
                    - description
