easy_admin:
    entities:
        Duration:
            class: App\Entity\Duration
            list:
                sort: ['displayOrder', 'ASC']
            show:
                - id
                - label
                - slug
                - displayOrder
            form:
                fields:
                    - label
                    - displayOrder
