easy_admin:
    entities:
        Person:
            class: App\Entity\Person
            list:
                title: People
                sort: ['lastname', 'ASC']
                fields:
                    - id
                    - firstname
                    - lastname
                    - { property: 'image', type: 'image', base_path: '%app.path.people_images%' }
                    - videos
            show:
                fields:
                    - id
                    - updatedAt
                    - firstname
                    - lastname
                    - slug
                    - { property: 'image', type: 'image', base_path: '%app.path.people_images%' }
                    - description
                    - videos
            form:
                fields:
                    - firstname
                    - lastname
                    - description
                    - { property: 'imageFile', type: 'vich_image' }
