easy_admin:
    entities:
        Person:
            class: App\Entity\Person
            list:
                title: People
                sort: ['lastname', 'ASC']
                fields:
                    - id
                    - firstname
                    - lastname
                    - videos
            form:
                fields:
                    - firstname
                    - lastname
                    - description
