easy_admin:
    entities:
        Video:
            class: App\Entity\Video
            controller: App\Controller\Admin\VideoController
            list:
                fields:
                    - id
                    - title
                    - { property: 'tags', type: 'array' }
                    - people
                    - duration
                    - level
            show:
                fields:
                    - id
                    - title
                    - slug
                    - url
                    - description
                    - { property: 'tags', type: 'array' }
                    - people
                    - duration
                    - level
            form:
                fields:
                    - title
                    - url
                    - description
                    - { property: 'people', type_options: { by_reference: false} }
                    - duration
                    - level
